version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    restart: on-failure
    container_name: client
    stdin_open: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    restart: on-failure
    container_name: server
    volumes:
      - /app/node_modules
      - ./server:/app
